name: CI
on: [ push, pull_request ]
jobs:
  Build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.5.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false # we rely on step outputs, no need for environment variables
        secrets: |
          secret/data/products/connectors/ci/common ARTIFACTORY_USR;
          secret/data/products/connectors/ci/common ARTIFACTORY_PSW;

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'maven'

    # Use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
    - name: 'Create settings.xml'
      uses: s4u/maven-settings-action@v2.8.0
      with:
        githubServer: false
        servers: |
          [{
             "id": "camunda-nexus",
             "username": "${{ steps.secrets.outputs.ARTIFACTORY_USR }}",
             "password": "${{ steps.secrets.outputs.ARTIFACTORY_PSW }}"
           }]
        mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "camunda-nexus", "name": "camunda Nexus"}]'

    - name: Build Maven Artifacts
      run: mvn verify -PcheckFormat
